spring: 
    profiles: 
        active: 
        - dev
    application:
        name: microservicecloud-config-eureka
---
server: 
    port: 7001
    
spring: 
    profiles: dev
    application:
        name: microservicecloud-config-eureka
        
eureka:
    instance: 
        hostname: eureka7001.com
    clinet:
        register-with-eureka: false
        fetch-registry: false
        service-url: 
            defaultZone: http://eureka7001.com:7001/eureka/
        serviceUrl: 
            defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
    port: 7001
    
spring: 
    profiles: test
    application:
        name: microservicecloud-config-eureka
        
eureka: 
    instance: 
        hostname: eureka7001.com
    clinet: 
        register-with-eureka: false
        fetch-registry: false
        service-url: 
            defaultZone: http://eureka7001.com:7001/eureka/
                        
